<a href="https://colab.research.google.com/github/umair594/100-Prediction-Models-/blob/main/Multinomial_Logistic_Regression_%E2%80%93_Multi_class_Classification_Model_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Project 8: Multinomial Logistic Regression – Multi-class Classification Model**

**Abstract**

Multinomial Logistic Regression is an extension of logistic regression for multi-class classification problems, where the target variable can take more than two categories. Unlike binary logistic regression, which models probabilities for two classes, multinomial logistic regression models probabilities for each class using the softmax function. This project explores the theory, implementation, and evaluation of a multinomial logistic regression model using Python. The performance is analyzed using metrics such as accuracy, confusion matrix, and classification report. Results demonstrate the effectiveness of this model for multi-class classification tasks with interpretable probabilistic outputs.

**Introduction**

Classification tasks often involve more than two categories. Common examples include:

Handwritten digit recognition (0–9 digits)

Animal species classification

Sentiment analysis (positive, neutral, negative)

Iris flower species prediction (Setosa, Versicolor, Virginica)

Multinomial logistic regression (also called softmax regression) is a natural extension of logistic regression to handle multi-class classification. This project aims to:

Understand multinomial logistic regression theory.

Implement a multi-class classifier in Python.

Evaluate performance on a synthetic dataset.

Analyze probability outputs and decision boundaries.

**Theory and Background**

Multi-class Classification

In multi-class classification, the target variable
𝑦
y can take
𝐾
K classes (
𝐾
>
2
K>2):
The goal is to predict the class label and its probability.

**Multinomial Logistic Regression**

For each class
𝑘
k, a linear combination of features is computed:
The softmax function converts these scores to probabilities:
Properties:

Probabilities sum to 1 across all classes.

Each coefficient vector
𝛽
𝑘
β
k
	​

 corresponds to a class.

**Decision Rule**

Predicted class is the one with the highest probability:

**Loss Function**

The model is trained using categorical cross-entropy (multi-class log loss):
Where
𝑦
𝑖
𝑘
y
ik
	​

 is 1 if sample
𝑖
i belongs to class
𝑘
k, 0 otherwise.

**Advantages**

Handles multiple classes naturally.

Provides probability estimates for each class.

Interpretable and computationally efficient.

Baseline for multi-class classification tasks.

**Limitations**

Assumes linear separability in feature space.

Sensitive to correlated features.

Performance may degrade with complex non-linear boundaries.

**Methodology**

Steps followed:

Generate a synthetic multi-class dataset.

Split dataset into training and testing sets.

Standardize features for numerical stability.

Train multinomial logistic regression using Python.

Predict class labels and probabilities.

Evaluate performance using accuracy, confusion matrix, and classification report.

# **Python Implementation**

**Import Libraries**

In [16]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

**Generate Multi-class Dataset**

In [17]:
X, y = make_classification(
    n_samples=500,
    n_features=10,
    n_informative=7,
    n_redundant=2,
    n_classes=3,
    n_clusters_per_class=1,
    random_state=42
)

**Train-Test Split**

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

**Feature Scaling**

In [19]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

**Train Multinomial Logistic Regression Model**

In [20]:
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=500)

model.fit(X_train_scaled, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=500, multi_class='multinomial')

**Predictions**

In [21]:
y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)

print("Predicted probabilities for first 5 samples:\n", y_prob[:5])

Predicted probabilities for first 5 samples:
 [[9.78415621e-04 9.99021534e-01 5.06434020e-08]
 [4.46246169e-02 5.08838572e-05 9.55324499e-01]
 [7.05323982e-01 2.95608531e-02 2.65115165e-01]
 [9.89005095e-01 2.29656113e-03 8.69834391e-03]
 [6.21775299e-03 5.90617278e-05 9.93723185e-01]]


**Model Evaluation**

In [22]:
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", cm)
print("Classification Report:\n", report)

Accuracy: 0.92
Confusion Matrix:
 [[26  0  4]
 [ 0 37  1]
 [ 2  1 29]]
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.87      0.90        30
           1       0.97      0.97      0.97        38
           2       0.85      0.91      0.88        32

    accuracy                           0.92       100
   macro avg       0.92      0.92      0.92       100
weighted avg       0.92      0.92      0.92       100



**Results and Discussion**

Accuracy: Measures overall correctness.

Confusion Matrix: Provides insight into class-wise performance.

Classification Report: Shows precision, recall, and F1-score for each class.

**Observations:**

The model correctly classifies most instances across three classes.

Probabilistic outputs allow threshold adjustment for specific applications.

Feature scaling significantly improves convergence of the solver.

**Advantages Observed**

Handles multi-class classification naturally without one-vs-rest splitting.

Provides interpretable class probabilities.

Efficient and widely used in academic and real-world applications.

**Limitations Observed**

Assumes linear relationships in log-odds space.

May underperform on complex, highly non-linear data.

Requires tuning solver and regularization parameters for large datasets.

**Conclusion**

Multinomial Logistic Regression effectively extends logistic regression to handle multi-class classification problems. By using the softmax function and categorical cross-entropy, the model outputs interpretable probability estimates for each class. Implementation in Python demonstrates strong performance on synthetic datasets and highlights the advantages of probabilistic classification. The approach serves as a robust baseline for multi-class problems and is suitable for applications requiring interpretable predictions.